name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: ["main"]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: env setting
        run: |
          echo "REACT_APP_FB_API_KEY=${{ secrets.REACT_APP_FB_API_KEY }}" >> .env
          echo "REACT_APP_FB_AUTH_DOMAIN=${{ secrets.REACT_APP_FB_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FB_PROJECT_ID=${{ secrets.REACT_APP_FB_PROJECT_ID }}" >> .env
          echo "REACT_APP_FB_STORAGE_BUCKET=${{ secrets.REACT_APP_FB_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_FB_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FB_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_FB_API_ID=${{ secrets.REACT_APP_FB_API_ID }}" >> .env
          echo "REACT_APP_FB_MEASUREMENT_ID=${{ secrets.REACT_APP_FB_MEASUREMENT_ID }}" >> .env
          echo "REACT_APP_SERVER=${{ secrets.REACT_APP_SERVER }}" >> .env
          echo "REACT_APP_EMAILJS_SERVICE_ID=${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}" >> .env
          echo "REACT_APP_EMAILJS_TEMPLATE_ID=${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "REACT_APP_EMAILJS_USER_ID=${{ secrets.REACT_APP_EMAILJS_USER_ID }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_0=${{ secrets.REACT_APP_YOUTUBE_API_KEY_0 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_1=${{ secrets.REACT_APP_YOUTUBE_API_KEY_1 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_2=${{ secrets.REACT_APP_YOUTUBE_API_KEY_2 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_3=${{ secrets.REACT_APP_YOUTUBE_API_KEY_3 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_4=${{ secrets.REACT_APP_YOUTUBE_API_KEY_4 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_5=${{ secrets.REACT_APP_YOUTUBE_API_KEY_5 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_6=${{ secrets.REACT_APP_YOUTUBE_API_KEY_6 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_7=${{ secrets.REACT_APP_YOUTUBE_API_KEY_7 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_8=${{ secrets.REACT_APP_YOUTUBE_API_KEY_8 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_9=${{ secrets.REACT_APP_YOUTUBE_API_KEY_9 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_10=${{ secrets.REACT_APP_YOUTUBE_API_KEY_10 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_11=${{ secrets.REACT_APP_YOUTUBE_API_KEY_11 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_12=${{ secrets.REACT_APP_YOUTUBE_API_KEY_12 }}" >> .env
          echo "REACT_APP_YOUTUBE_API_KEY_13=${{ secrets.REACT_APP_YOUTUBE_API_KEY_13 }}" >> .env


      - name: Build
        run: npm ci && npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: mylist-a6a35
