name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: ["develop"]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: .env setting
        run: |
          echo "REACT_APP_FB_API_KEY=${{ secrets.REACT_APP_FB_API_KEY }}" >> .env
          echo "REACT_APP_FB_AUTH_DOMAIN=${{ secrets.REACT_APP_FB_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FB_PROJECT_ID=${{ secrets.REACT_APP_FB_PROJECT_ID }}" >> .env
          echo "REACT_APP_FB_STORAGE_BUCKET=${{ secrets.REACT_APP_FB_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_FB_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FB_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_FB_APP_ID=${{ secrets.REACT_APP_FB_APP_ID }}" >> .env
          echo "REACT_APP_FB_MEASUREMENT_ID=${{ secrets.REACT_APP_FB_MEASUREMENT_ID }}" >> .env
          echo "REACT_APP_SERVER=${{ secrets.REACT_APP_SERVER }}" >> .env

      - name: Build
        run: npm ci && npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: mylist-a6a35
